### ISSUE TITLE
Ive been trying to get packwiz to update from github but i just cant figure it out even using the example pack

### ISSUE THREAD

**Issue by NTCatx** [comp500/packwiz-installer#78]
I've used so many variations of this 

"$INST_JAVA" -jar packwiz-installer-bootstrap.jar https://github.com/packwiz/packwiz-example-pack/blob/v1/pack.toml

i just cant figure it out

ParseError(errorDescription=token recognition error at: '<', line=7, cause=LexerNoViableAltException('<'))
	at cc.ekblad.toml.serialization.TomlErrorListener.syntaxError(SourceFile:21)
	at org.antlr.v4.runtime.ProxyErrorListener.syntaxError(SourceFile:41)
	at org.antlr.v4.runtime.Lexer.notifyListeners(SourceFile:364)
	at org.antlr.v4.runtime.Lexer.nextToken(SourceFile:144)
	at org.antlr.v4.runtime.BufferedTokenStream.fetch(SourceFile:169)
	at org.antlr.v4.runtime.BufferedTokenStream.sync(SourceFile:152)
	at org.antlr.v4.runtime.BufferedTokenStream.consume(SourceFile:136)
	at org.antlr.v4.runtime.Parser.consume(SourceFile:570)
	at org.antlr.v4.runtime.Parser.match(SourceFile:204)
	at cc.ekblad.toml.parser.TomlParser.document(SourceFile:151)
	at cc.ekblad.toml.serialization.TomlDeserializerKt.from(SourceFile:49)
	at cc.ekblad.toml.serialization.TomlDeserializerKt.from(SourceFile:28)
	at link.infra.packwiz.installer.UpdateManager.start(SourceFile:488)
	at link.infra.packwiz.installer.UpdateManager.<init>(SourceFile:42)
	at link.infra.packwiz.installer.Main.startup(SourceFile:112)
	at link.infra.packwiz.installer.Main.<init>(SourceFile:154)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:480)
	at link.infra.packwiz.installer.bootstrap.LoadJAR.start(LoadJAR.java:51)
	at link.infra.packwiz.installer.bootstrap.Main.<init>(Main.java:91)
	at link.infra.packwiz.installer.bootstrap.Main.main(Main.java:46)
Caused by: LexerNoViableAltException('<')
	at org.antlr.v4.runtime.atn.LexerATNSimulator.failOrAccept(SourceFile:309)
	at org.antlr.v4.runtime.atn.LexerATNSimulator.execATN(SourceFile:230)
	at org.antlr.v4.runtime.atn.LexerATNSimulator.match(SourceFile:114)
	at org.antlr.v4.runtime.Lexer.nextToken(SourceFile:141)
	... 20 more

**Comment by Hri7566** [comment]
The URL you are using to download the pack is pointing to a GitHub web page. It's downloading HTML instead of the `pack.toml` file.

Use the raw link to the file instead:
https://raw.githubusercontent.com/packwiz/packwiz-example-pack/v1/pack.toml

![image](https://github.com/packwiz/packwiz-installer/assets/18133844/38d3eda3-5802-4416-94ba-a5dd33262189)

**Comment by NTCatx** [comment]
thank you so much, i was too dumb to figure that out lol
