### ISSUE TITLE
[error] Malformed input or input contains unmappable characters

### ISSUE THREAD

**Issue by MimzyFang** [comp500/packwiz-installer#79]
filename: §6§lS§euper §6§lD§euper §6§lV§eanilla §5§lReima§d§lgined §c[§f 1.0.3 §bPRE §c].zip
source of file: https://modrinth.com/shader/super-duper-vanilla-reimagined/version/1.0.3
```
[FATAL] Update process failed: 
java.nio.file.InvalidPathException: Malformed input or input contains unmappable characters: shaderpacks/?6?lS?euper ?6?lD?euper ?6?lV?eanilla ?5?lReima?d?lgined ?c[?f 1.0.3 ?bPRE ?c].zip
	at java.base/sun.nio.fs.UnixPath.encode(UnixPath.java:121)
	at java.base/sun.nio.fs.UnixPath.<init>(UnixPath.java:68)
	at java.base/sun.nio.fs.UnixFileSystem.getPath(UnixFileSystem.java:279)
	at java.base/java.nio.file.Path.of(Path.java:147)
	at java.base/java.nio.file.Paths.get(Paths.java:69)
	at okio.Path.toNioPath(SourceFile:103)
	at link.infra.packwiz.installer.target.path.PackwizFilePath.getNioPath(SourceFile:22)
	at link.infra.packwiz.installer.UpdateManager.start(SourceFile:145)
	at link.infra.packwiz.installer.UpdateManager.<init>(SourceFile:42)
	at link.infra.packwiz.installer.Main.startup(SourceFile:112)
	at link.infra.packwiz.installer.Main.<init>(SourceFile:154)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:480)
	at link.infra.packwiz.installer.bootstrap.LoadJAR.start(LoadJAR.java:51)
	at link.infra.packwiz.installer.bootstrap.Main.<init>(Main.java:91)
	at link.infra.packwiz.installer.bootstrap.Main.main(Main.java:46)
```

metadata:
```toml
name = "Super Duper Vanilla Reimagined"
filename = "§6§lS§euper §6§lD§euper §6§lV§eanilla §5§lReima§d§lgined §c[§f 1.0.3 §bPRE §c].zip"
side = "client"

[download]
url = "https://cdn.modrinth.com/data/CiFGzRV9/versions/EXglF6Ud/%C2%A76%C2%A7lS%C2%A7euper%20%C2%A76%C2%A7lD%C2%A7euper%20%C2%A76%C2%A7lV%C2%A7eanilla%20%C2%A75%C2%A7lReima%C2%A7d%C2%A7lgined%20%C2%A7c%5B%C2%A7f%201.0.3%20%C2%A7bPRE%20%C2%A7c%5D.zip"
hash-format = "sha1"
hash = "08abeb97e1ff31d65eb5e356821654ee0407f138"

[update]
[update.modrinth]
mod-id = "CiFGzRV9"
version = "EXglF6Ud"
```

**Comment by comp500** [comment]
Make sure that your .pw.toml file is using the right encoding. If you use anything other than UTF-8, you're likely to run into issues!

**Comment by JustCoderdev** [comment]
How did you solve this issue?

**Comment by MimzyFang** [comment]
> How did you solve this issue?

I changed the filename = "" content
