### ISSUE TITLE
I can't install MTR-LU-Addon-fabric-1.19.2-2.1.1.jar

### ISSUE THREAD

**Issue by IF-chan** [comp500/packwiz-installer#81]
java.net.SocketTimeoutException: timeout
	at okhttp3.internal.http2.Http2Stream$StreamTimeout.newTimeoutException(SourceFile:675)
	at okhttp3.internal.http2.Http2Stream$StreamTimeout.exitAndThrowIfTimedOut(SourceFile:684)
	at okhttp3.internal.http2.Http2Stream$FramingSource.read(SourceFile:379)
	at okhttp3.internal.connection.Exchange$ResponseBodySource.read(SourceFile:276)
	at okio.RealBufferedSource.read(SourceFile:192)
	at okio.ForwardingSource.read(SourceFile:27)
	at okio.HashingSource.read(SourceFile:70)
	at okio.ForwardingSource.read(SourceFile:27)
	at okio.RealBufferedSource.readAll(SourceFile:287)
	at link.infra.packwiz.installer.DownloadTask.download(SourceFile:251)
	at link.infra.packwiz.installer.UpdateManager.processIndex$lambda$15$lambda$14(SourceFile:362)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:840)

**Comment by zbx1425** [comment]
……我是没想到在这儿还能看到 MTR 玩家 🤣；MTR LetsPlay 模组包里这个文件是从 Github Pages 提供的，如果您在国内没挂全局代理，下不下来在所难免。

---

For maintainer: This is likely just network issue.
